// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnPNDJBYD8sHB9NhKTdEEXUQzbHb3W_Mk',
    appId: '1:1084479234439:web:4dc39bbf2ff2f83fc33322',
    messagingSenderId: '1084479234439',
    projectId: 'cineetec-6ce8a',
    authDomain: 'cineetec-6ce8a.firebaseapp.com',
    storageBucket: 'cineetec-6ce8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSFiGYfn53I3paK_mcftaVmVhE1rhu2wk',
    appId: '1:1084479234439:android:3bd8c475f2863170c33322',
    messagingSenderId: '1084479234439',
    projectId: 'cineetec-6ce8a',
    storageBucket: 'cineetec-6ce8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhyMH1PMLkVZuhYLv_PEDJ3Zql_U82mbE',
    appId: '1:1084479234439:ios:c51507e6abf59e8fc33322',
    messagingSenderId: '1084479234439',
    projectId: 'cineetec-6ce8a',
    storageBucket: 'cineetec-6ce8a.firebasestorage.app',
    iosBundleId: 'com.example.projetoBancoDados',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhyMH1PMLkVZuhYLv_PEDJ3Zql_U82mbE',
    appId: '1:1084479234439:ios:c51507e6abf59e8fc33322',
    messagingSenderId: '1084479234439',
    projectId: 'cineetec-6ce8a',
    storageBucket: 'cineetec-6ce8a.firebasestorage.app',
    iosBundleId: 'com.example.projetoBancoDados',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnPNDJBYD8sHB9NhKTdEEXUQzbHb3W_Mk',
    appId: '1:1084479234439:web:a36af8400c25200ec33322',
    messagingSenderId: '1084479234439',
    projectId: 'cineetec-6ce8a',
    authDomain: 'cineetec-6ce8a.firebaseapp.com',
    storageBucket: 'cineetec-6ce8a.firebasestorage.app',
  );
}
