// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdDuxNpCJpfNueUbQYD8VHf9K7IpRBXJk',
    appId: '1:300942605158:web:f1f9436d4322db089fa6a7',
    messagingSenderId: '300942605158',
    projectId: 'projetoecotrackba',
    authDomain: 'projetoecotrackba.firebaseapp.com',
    storageBucket: 'projetoecotrackba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_iiBQl3npxI-1FoionH22UxJCj2H6h_M',
    appId: '1:300942605158:android:698242dd9aa17f769fa6a7',
    messagingSenderId: '300942605158',
    projectId: 'projetoecotrackba',
    storageBucket: 'projetoecotrackba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBDJhLQlnuKX3JNmUJtQ7xv3eivDqJT20',
    appId: '1:300942605158:ios:304ba97a48c939989fa6a7',
    messagingSenderId: '300942605158',
    projectId: 'projetoecotrackba',
    storageBucket: 'projetoecotrackba.firebasestorage.app',
    iosBundleId: 'com.example.appEcotrack3a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBDJhLQlnuKX3JNmUJtQ7xv3eivDqJT20',
    appId: '1:300942605158:ios:304ba97a48c939989fa6a7',
    messagingSenderId: '300942605158',
    projectId: 'projetoecotrackba',
    storageBucket: 'projetoecotrackba.firebasestorage.app',
    iosBundleId: 'com.example.appEcotrack3a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdDuxNpCJpfNueUbQYD8VHf9K7IpRBXJk',
    appId: '1:300942605158:web:61eafb740e38528c9fa6a7',
    messagingSenderId: '300942605158',
    projectId: 'projetoecotrackba',
    authDomain: 'projetoecotrackba.firebaseapp.com',
    storageBucket: 'projetoecotrackba.firebasestorage.app',
  );

}